"""Add ProductPriceHistory table and update Product model

Revision ID: ae3ac232bf21
Revises: 
Create Date: 2024-12-07 15:31:52.029021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3ac232bf21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new ProductPriceHistory table
    op.create_table(
        'product_price_histories',
        sa.Column('history_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('old_price', sa.Float(), nullable=False),
        sa.Column('new_price', sa.Float(), nullable=False),
        sa.Column('change_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_product_price_histories_history_id'), 'product_price_histories', ['history_id'], unique=False)

    # Other changes to the Product model, if any
    # (e.g., ensuring price is nullable)
    op.alter_column('products', 'price', existing_type=sa.Float(), nullable=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
